### PR TITLE
Make Travis and Tox play more nicely together

### PR DESCRIPTION
**Pull request by singingwolfboy**
https://www.dominicrodger.com/tox-and-travis.html

### CODE REVIEW

**Comment by winhamwr** [comment]
Hi David,

That's pretty slick! Thanks for the contribution.

-Wes

**Comment by singingwolfboy** [comment]
Welcome! As an aside, the tests are failing on master. I'd love to hack on this project (partially because I want to use it in one of my projects!), but I don't trust projects with failing tests. Can you fix it? :)

**Comment by winhamwr** [comment]
> I don't trust projects with failing tests

I understand completely.

> Can you fix it? :)

I sure hope so. I think most of our tests are suffering from celery/django-celery#295 because of a mismatched combination of django-celery and celery, as [described here](https://github.com/celery/django-celery/issues/295#issuecomment-39094343). Our test requirements aren't creating the proper combination, so nonsense occurs.

I'm working on [other version compatibilities](https://github.com/nosedjango/nosedjango/pull/34) today, but I at least have a very strong desire to have passing tests, here. Not that this helps you at all :)

-Wes

**Comment by winhamwr** [comment]
Hi David,

You inspired me to push out #46 which includes a passing Travis build and additions to tox.ini to support testing in other versions of django/celery.

Thanks :)
-Wes

**Comment by singingwolfboy** [comment]
Super cool! :sunglasses:

**Pull request merged**
